- name: "Desktop-Base + Common packages"
  description: "Recommended. Don't change unless you know what you're doing."
  hidden: false
  selected: true
  critical: false
  subgroups:
      - name: "X11"
        description: "Default X11 system"
        selected: true
        packages:
           - libwnck3
           - mesa-utils
           - xf86-input-libinput
           - xorg-xdpyinfo
           - xorg-server
           - xorg-xinit
           - xorg-xinput
           - xorg-xkill
           - xorg-xrandr
      - name: "GPU drivers"
        description: "Graphics hardware drivers"
        selected: true
        packages:
          - xf86-video-amdgpu
      - name: "Network"
        description: "Network apps drivers and tools"
        selected: true
        packages:
          - b43-fwcutter
          - dhclient
          - dnsmasq
          - ethtool
          - gnu-netcat
          - iwd
          - modemmanager
          - nbd
          - ndisc6
          - networkmanager
          - networkmanager-openvpn
          - nmap
          - nss-mdns
          - openconnect
          - openvpn
          - ppp
          - pptpclient
          - rp-pppoe
          - sshfs
          - usb_modeswitch
          - vpnc
          - whois
          - wireless-regdb
          - wireless_tools
          - wpa_supplicant
          - xl2tpd
      - name: "Package management"
        description: "Packages tools"
        selected: true
        packages:
          - base-devel
          - pacman-contrib
          - pkgfile
          - rebuild-detector
          - yay
      - name: "Desktop integration"
        description: "Useful helper tools and libs for desktop usage"
        selected: true
        packages:
          - accountsservice
          - bash-completion
          - bluez
          - bluez-utils
          - ffmpegthumbnailer
          - gst-libav
          - gst-plugin-pipewire
          - gst-plugins-bad
          - gst-plugins-ugly
          - libdvdcss
          - libgsf
          - libopenraw
          - mlocate
          - poppler-glib
          - xdg-user-dirs
          - xdg-utils
      - name: "Filesystem"
        description: "Filesystem tools and apps"
        selected: true
        packages:
          - haveged
          - nfs-utils
          - nilfs-utils
          - ntp
          - smartmontools
          - udisks2
          - unrar
          - unzip
          - xz
      - name: "Fonts"
        description: "EndeavourOS font selection"
        selected: true
        packages:
          - adobe-source-han-sans-cn-fonts
          - adobe-source-han-sans-jp-fonts
          - adobe-source-han-sans-kr-fonts
          - cantarell-fonts
          - freetype2
          - noto-fonts
          - ttf-bitstream-vera
          - ttf-dejavu
          - ttf-liberation
          - ttf-opensans
      - name: "Audio"
        description: "Audio handling tools apps and libs"
        selected: true
        packages:
          - alsa-firmware
          - alsa-plugins
          - alsa-utils
          - pavucontrol
          - pipewire-pulse
          - pipewire-alsa
          - pipewire-jack
          - rtkit
          - wireplumber
      - name: "Hardware"
        description: "Hardware support libs and firmware"
        selected: true
        packages:
          - dmidecode
          - hdparm
          - hwdetect
          - mtools
          - sof-firmware
      - name: "Power"
        description: "Powermanagement support"
        selected: true
        packages:
          - power-profiles-daemon
          - upower
- name: "EndeavourOS applications"
  description: "EndeavourOS tools and applications"
  hidden: false
  selected: true
  critical: true
  packages:
    - endeavouros-theming
    - eos-apps-info
    - eos-hooks
    - eos-log-tool
    - eos-packagelist
    - eos-quickstart
    - eos-rankmirrors
    - eos-update-notifier
    - pahis
    - welcome
- name: "Recommended applications selection"
  description: "General tools and applications"
  hidden: false
  selected: true
  critical: true
  packages:
    - duf
    - findutils
    - fsarchiver
    - git
    - glances
    - inxi
    - lsb-release
    - meld
    - nano-syntax-highlighting
    - neofetch
    - pv
    - python-defusedxml
    - python-packaging
    - rsync
    - tldr
    - sed
    - sudo
    - vi
    - xed
    - xterm
    - wget
- name: "Firefox and language package"
  description: "Add firefox and language pack if possible"
  hidden: false
  selected: true
  critical: true
  packages:
    - firefox
    - firefox-i18n-$LOCALE
- name: "Firewall"
  description: "Firewall support"
  hidden: false
  selected: true
  critical: true
  packages:
    - firewalld
    - python-pyqt5
    - python-capng
- name: "Printing Support"
  description: "Support for printing (Cups)"
  hidden: false
  selected: false
  critical: true
  packages:
    - cups
    - cups-filters
    - cups-pdf
    - foomatic-db
    - foomatic-db-engine
    - foomatic-db-gutenprint-ppds
    - foomatic-db-nonfree
    - foomatic-db-nonfree-ppds
    - foomatic-db-ppds
    - ghostscript
    - gsfonts
    - gutenprint
    - splix
    - system-config-printer
- name: "HP printer/scanner support"
  description: "Packages for HP printer/scanner"
  hidden: false
  selected: false
  critical: true
  packages:
    - hplip
    - python-pyqt5
    - python-reportlab
    - xsane
    - cups
    - cups-filters
    - cups-pdf
