- id: bspwm
  hidden: true
  selected: false
  expanded: false
- id: openbox
  hidden: true
  selected: false
  expanded: false
- id: qtile
  hidden: true
  selected: false
  expanded: false
- id: sway
  hidden: true
  selected: false
  expanded: false
- id: worm
  hidden: true
  selected: false
  expanded: false
- name: "Printing-Support"
  description: "Support for printing (Cups)"
  hidden: false
  selected: false
  critical: false
  packages:
    - cups
    - cups-filters
    - cups-pdf
    - ghostscript
    - gsfonts
    - foomatic-db-engine
    - foomatic-db
    - foomatic-db-ppds
    - foomatic-db-nonfree
    - foomatic-db-nonfree-ppds 
    - gutenprint 
    - foomatic-db-gutenprint-ppds
    - splix
    - system-config-printer
- name: "Support for HP Printer/Scanner"
  description: "Extra Packages for HP Printer/Scanner"
  hidden: false
  selected: false
  critical: false
  packages:
    - hplip
    - python-pyqt5
    - python-reportlab
    - xsane
    - cups
    - cups-filters
    - cups-pdf
- name: "Accessibility Tools"
  description: "Screen reader and mouse tweaks (impaired vision)"
  hidden: false
  selected: false
  critical: false
  packages:
    - orca
    - mousetweaks
    - espeak-ng
