- name: "Desktop-Base + Common packages"
  description: "Recommended. Don't change unless you know what you're doing (generic)."
  hidden: true
  selected: false
  critical: false
  subgroups:
      - name: "X-system"
        description: "Default X-system"
        selected: false
        packages:
           - libwnck3
           - mesa-utils
           - xf86-input-libinput
           - xorg-xdpyinfo
           - xorg-server
           - xorg-xinit
           - xorg-xinput
           - xorg-xkill
           - xorg-xrandr
      - name: "GPU drivers"
        description: "Graphics hardware drivers"
        selected: false
        packages:
          - xf86-video-amdgpu
      - name: "Network"
        description: "Network apps drivers and tools"
        selected: false
        packages:
          - b43-fwcutter
          - dhclient
          - dnsmasq
          - ethtool
          - gnu-netcat
          - iwd
          - modemmanager
          - nbd
          - ndisc6
          - networkmanager
          - networkmanager-openvpn
          - nmap
          - nss-mdns
          - openconnect
          - openvpn
          - ppp
          - pptpclient
          - rp-pppoe
          - sshfs
          - usb_modeswitch
          - vpnc
          - whois
          - wireless-regdb
          - wireless_tools
          - wpa_supplicant
          - xl2tpd
      - name: "firewall"
        description: "Firewall support"
        selected: false
        packages:
          - firewalld
          - python-pyqt5
          - python-capng
      - name: "packages management"
        description: "Packages tools"
        selected: false
        packages:
          - base-devel
          - pacman-contrib
          - pkgfile
          - rebuild-detector
          - yay
      - name: "desktop integration"
        description: "Useful helper tools and libs for desktop usage"
        selected: false
        packages:
          - accountsservice
          - bash-completion
          - bluez
          - bluez-utils
          - ffmpegthumbnailer
          - gst-libav
          - gst-plugin-pipewire
          - gst-plugins-bad
          - gst-plugins-ugly
          - libdvdcss
          - libgsf
          - libopenraw
          - mlocate
          - poppler-glib
          - xdg-user-dirs
          - xdg-utils
      - name: "filesystem"
        description: "Filesystem tools and apps"
        selected: false
        packages:
          - haveged
          - nfs-utils
          - nilfs-utils
          - ntp
          - smartmontools
          - udisks2
          - unrar
          - unzip
          - xz
      - name: "fonts"
        description: "EndeavourOS font selection"
        selected: false
        packages:
          - adobe-source-han-sans-cn-fonts
          - adobe-source-han-sans-jp-fonts
          - adobe-source-han-sans-kr-fonts
          - cantarell-fonts
          - freetype2
          - noto-fonts
          - ttf-bitstream-vera
          - ttf-dejavu
          - ttf-liberation
          - ttf-opensans
      - name: "audio"
        description: "Audio handling tools apps and libs"
        selected: false
        packages:
          - alsa-firmware
          - alsa-plugins
          - alsa-utils
          - pavucontrol
          - pipewire-pulse
          - pipewire-alsa
          - pipewire-jack
          - rtkit
          - wireplumber
      - name: "hardware"
        description: "Hardware support libs and firmware"
        selected: false
        packages:
          - dmidecode
          - dmraid
          - hdparm
          - hwdetect
          - mtools
          - sof-firmware
      - name: "power"
        description: "Powermanagement support"
        selected: false
        packages:
          - power-profiles-daemon
          - upower
      - name: "EndeavourOS Apps"
        description: "EndeavourOS tools and applications"
        selected: false
        packages:
          - endeavouros-theming
          - eos-apps-info
          - eos-hooks
          - eos-log-tool
          - eos-packagelist
          - eos-quickstart
          - eos-rankmirrors
          - eos-update-notifier
          - pahis
          - welcome
      - name: "EndeavourOS applications selection"
        description: "General tools and applications"
        selected: false
        packages:
          - duf
          - findutils
          - fsarchiver
          - git
          - glances
          - inxi
          - lsb-release
          - meld
          - nano-syntax-highlighting
          - neofetch
          - pv
          - python-defusedxml
          - python-packaging
          - rsync
          - tldr
          - sed
          - sudo
          - vi
          - xed
          - xterm
          - wget
- name: "Firefox and language package"
  description: "Add firefox and language pack if possible"
  hidden: true
  selected: false
  critical: false
  packages:
    - firefox
    - firefox-i18n-$LOCALE
- name: "XFCE4-Desktop"
  description: "XFCE4 - lightweight desktop fast and low on system resources, visually appealing and user friendly."
  hidden: false
  selected: false
  expanded: false
  critical: true
  subgroups:
      - name: "EndeavourOS-theming"
        description: "EndeavourOS XFCE4 theming (unselect to install vanilla)"
        selected: false
        packages:
            - arc-gtk-theme-eos
            - eos-lightdm-slick-theme
            - eos-qogir-icons
            - endeavouros-skel-xfce4
            - endeavouros-xfce4-terminal-colors
      - name: "XFCE4-Desktop"
        description: "XFCE4 needed packages"
        selected: false
        packages:
         - blueman
         - file-roller
         - galculator
         - gvfs
         - gvfs-afc
         - gvfs-gphoto2
         - gvfs-mtp
         - gvfs-nfs
         - gvfs-smb
         - lightdm
         - lightdm-slick-greeter
         - network-manager-applet
         - parole
         - ristretto
         - thunar-archive-plugin
         - thunar-media-tags-plugin
         - xdg-user-dirs-gtk
         - xed
         - xfce4
         - xfce4-battery-plugin
         - xfce4-datetime-plugin
         - xfce4-mount-plugin
         - xfce4-netload-plugin
         - xfce4-notifyd
         - xfce4-pulseaudio-plugin
         - xfce4-screensaver
         - xfce4-screenshooter
         - xfce4-taskmanager
         - xfce4-wavelan-plugin
         - xfce4-weather-plugin
         - xfce4-whiskermenu-plugin
         - xfce4-xkb-plugin
- name: "i3-Window-Manager"
  description: "i3 tiling window manager, primarily targeted at developers and advanced users."
  hidden: false
  selected: false
  expanded: false
  critical: true
  packages:
    - acpi
    - arandr
    - arc-gtk-theme-eos
    - archlinux-xdg-menu
    - awesome-terminal-fonts
    - dex
    - dmenu
    - dunst
    - endeavouros-skel-i3wm
    - endeavouros-xfce4-terminal-colors
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - feh
    - file-roller
    - galculator
    - gthumb
    - gtk-engine-murrine
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - i3-gaps
    - i3blocks
    - i3lock
    - i3status
    - jq
    - lightdm
    - lightdm-slick-greeter
    - lxappearance-gtk3
    - mpv
    - network-manager-applet
    - numlockx
    - playerctl
    - polkit-gnome
    - rofi
    - scrot
    - sysstat
    - thunar
    - thunar-archive-plugin
    - thunar-volman
    - tumbler
    - xbindkeys
    - xdg-user-dirs-gtk
    - xed
    - xfce4-terminal
    - xorg-xbacklight
    - xorg-xdpyinfo
- name: "KDE-Desktop"
  description: "KDE-Plasma Desktop - Simple by default, powerful when needed."
  hidden: false
  selected: false
  critical: true
  packages:
    - ark
    - audiocd-kio
    - bluedevil
    - breeze-gtk
    - dolphin
    - dragon
    - elisa
    - eos-plasma-sddm-config
    - eos-settings-plasma
    - gwenview
    - kcalc
    - kate
    - kdeconnect
    - kde-gtk-config
    - khotkeys
    - kinfocenter
    - kinit
    - kio-fuse
    - konsole
    - kscreen
    - kwallet-pam
    - okular
    - plasma-desktop
    - plasma-disks
    - plasma-nm
    - plasma-pa
    - plasma-wayland-session
    - powerdevil
    - print-manager
    - sddm-kcm
    - solid
    - spectacle
    - xsettingsd
- name: "GNOME-Desktop"
  description: "GNOME Desktop - designed to put you in control and get things done."
  hidden: false
  selected: false
  critical: true
  packages:
    - adwaita-icon-theme
    - arc-gtk-theme-eos
    - eos-settings-gnome
    - eos-qogir-icons
    - eog
    - evince
    - file-roller
    - gdm
    - gnome-calculator
    - gnome-console
    - gnome-control-center
    - gnome-disk-utility
    - gnome-keyring
    - gnome-nettool
    - gnome-power-manager
    - gnome-screenshot
    - gnome-shell
    - gnome-text-editor
    - gnome-themes-extra
    - gnome-tweaks
    - gnome-usage
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - nautilus
    - nautilus-sendto
    - sushi
    - totem
    - xdg-user-dirs-gtk
- name: "MATE-Desktop"
  description: "MATE Desktop - the continuation of GNOME 2"
  hidden: false
  selected: false
  critical: true
  packages:
    - arc-gtk-theme-eos
    - eos-settings-mate
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - celluloid
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - lightdm
    - lightdm-slick-greeter
    - mate
    - mate-extra
    - network-manager-applet
    - xdg-user-dirs-gtk
- name: "Cinnamon-Desktop"
  description: "Cinnamon Desktop - advanced innovative features and a traditional user experience."
  hidden: false
  selected: false
  critical: true
  packages:
    - arc-gtk-theme-eos
    - celluloid
    - cinnamon
    - cinnamon-translations
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - eos-settings-cinnamon
    - file-roller
    - gnome-calculator
    - gnome-screenshot
    - gnome-system-monitor
    - gnome-terminal
    - gthumb
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - lightdm
    - lightdm-slick-greeter
    - nemo-fileroller
    - nemo-image-converter
    - nemo-preview
    - nemo-share
    - x-apps
    - xdg-user-dirs-gtk
- name: "Budgie-Desktop"
  description: "Budgie - an independent, familiar, and modern desktop."
  hidden: false
  selected: false
  critical: true
  packages:
    - arc-gtk-theme-eos
    - eos-settings-budgie
    - eos-lightdm-slick-theme
    - eos-qogir-icons
    - budgie-control-center
    - budgie-desktop
    - budgie-desktop-view
    - budgie-extras
    - budgie-screensaver
    - eog
    - evince
    - file-roller
    - gedit
    - gnome-keyring
    - gnome-screenshot
    - gnome-terminal
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - lightdm
    - lightdm-slick-greeter
    - nemo
    - nemo-fileroller
    - nemo-preview
    - network-manager-applet
    - sushi
    - totem
    - xdg-user-dirs-gtk
- name: "LXQT-Desktop"
  description: "The Lightweight Qt Desktop Environment."
  hidden: false
  selected: false
  critical: true
  packages:
    - audiocd-kio
    - baka-mplayer
    - breeze
    - breeze-gtk
    - eos-settings-lxqt
    - eos-sddm-theme
    - featherpad
    - gvfs
    - gvfs-mtp
    - kio-fuse
    - libstatgrab
    - libsysstat
    - lm_sensors
    - lxqt
    - lxqt-archiver
    - network-manager-applet
    - oxygen-icons
    - pavucontrol-qt
    - print-manager
    - qt5-translations
    - xdg-utils
    - xscreensaver
    - xsettingsd
- name: "LXDE-Desktop"
  description: "The Lightweight Desktop Environment."
  hidden: false
  selected: false
  critical: true
  packages:
    - arc-gtk-theme-eos
    - eos-settings-lxde
    - eos-lxdm-gtk3
    - eos-qogir-icons
    - celluloid
    - file-roller
    - galculator
    - gnome-screenshot
    - gpicview
    - gvfs
    - gvfs-afc
    - gvfs-gphoto2
    - gvfs-mtp
    - gvfs-nfs
    - gvfs-smb
    - lxappearance-gtk3
    - obconf
    - lxde-common
    - lxde-icon-theme
    - lxhotkey-gtk3
    - lxinput-gtk3
    - lxlauncher-gtk3
    - lxpanel-gtk3
    - lxrandr-gtk3
    - lxsession-gtk3
    - lxtask-gtk3
    - lxterminal
    - notification-daemon
    - openbox
    - pcmanfm-gtk3
    - lxmusic
    - network-manager-applet
    - xdg-user-dirs-gtk
    - xed
- name: "Printing-Support"
  description: "Support for printing (Cups)"
  hidden: false
  selected: false
  critical: true
  packages:
    - cups
    - cups-filters
    - cups-pdf
    - foomatic-db
    - foomatic-db-engine
    - foomatic-db-gutenprint-ppds
    - foomatic-db-nonfree
    - foomatic-db-nonfree-ppds
    - foomatic-db-ppds
    - ghostscript
    - gsfonts
    - gutenprint
    - splix
    - system-config-printer
- name: "Support for HP Printer/Scanner"
  description: "Extra Packages for HP Printer/Scanner"
  hidden: false
  selected: false
  critical: true
  packages:
    - hplip
    - python-pyqt5
    - python-reportlab
    - xsane
    - cups
    - cups-filters
    - cups-pdf
- name: "Accessibility Tools"
  description: "Screen reader and mouse tweaks (impaired vision)"
  hidden: false
  selected: false
  critical: true
  packages:
    - espeak-ng
    - mousetweaks
    - orca
